version:  '2.0'
services: 
  mongo:
    image: mongo
    volumes: ["./database:/data/db"]
    networks:
      loco:
        ipv4_address: 10.10.10.2
  mongo-shell:
    image: mongo
    volumes: ["./database:/data/db"]
    tty: true
    stdin_open: true
    networks:
      loco:
        ipv4_address: 10.10.10.3
    depends_on:
      - mongo
  shell:
    image: mdjango
    volumes: ["./backend:/usr/src/app"]
    stdin_open: true
    tty: true
    networks:
      loco:
        ipv4_address: 10.10.10.4

networks:
  loco:
    driver: 'bridge'
    ipam:
      config:
        - subnet: 10.10.10.0/10
          gateway: 10.10.10.1